Repository bonitasoft/bonita-documentation-theme, pull requests merged in 2022-11, with the labels that each got.

#150 fix: display the images in footer and "edit this page"
  src/partials/footer-content.hbs
  src/partials/page-additional-icons.hbs
  src/partials/toolbar.hbs
Labels: bug

#148 chore(deps): update package-lock.json after highlight.js removal
  package-lock.json
Labels: dependencies, javascript

#151 feat: improve wording of the 404 page
  src/img/404-error-bonita-flavor.png
  src/partials/article-404.hbs
Labels: enhancement

#153 feat(page_icons): Always display the page icons
  src/stylesheets/toolbar.scss
Labels: enhancement
