Repository bonitasoft/bonita-documentation-theme, pull requests merged in 2023-05, with the labels that each got.

#184 feat(icon): add font-awesome support
  gulp.d/tasks/build.js
  package-lock.json
  package.json
  preview-src/icons.adoc
  preview-src/ui-model.yml
  src/stylesheets/components/colors.scss
  src/stylesheets/site.scss
Labels: enhancement

#186 refactor: Fix format issue
  gulp.d/tasks/build.js
Labels: bug

#187 feat: let display the search bar in preview
  preview-src/ui-model.yml
  src/helpers/isSearchBarDisplayed.js
Labels: enhancement

#188 chore: create .nvmrc
  .github/actions/build-setup/action.yml
  .nvmrc
Labels: ignore-for-release-notes
